

disabled-worlds:
  - 'disabled-world-1'
  - 'disabled-world-2'

# Hologram Settings
hologram-settings:
  enabled: true
  y-offset: 1
  # Time in seconds until hologram is deleted
  duration: 5
  # Should the hologram be destroyed when the table is
  sync-holograms: true
  text-display: true

  # Should there be items under the hologram when you craft?
  item-display: true
  # Configure the Item Settings
  item-settings:
    # Leave as normal, Custom Items are coming soon.
    type: 'NORMAL'

  # Format of text on hologram
  format:
    - '&b» &fYou have crafted &bx%amount% &f%item% &b«'

# Sound Settings
sound-settings:
  enabled: true
  # If false, sounds will play for anyone standing near the crafting table
  player-only: true
  # Find list of available sounds here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  sound: 'ENTITY_ARROW_HIT_PLAYER'
  volume: 100

# Particle Settings | Requires PlayerParticles (https://www.spigotmc.org/resources/playerparticles.40261/)
particle-settings:
  enabled: true
  # Unavailable Particles: BLOCK_CRACK, DUST, ITEM_CRACK, FALLING_DUST
  # Particles: https://github.com/Esophose/PlayerParticles/blob/master/src/main/java/dev/esophose/playerparticles/particles/ParticleEffect.java
  particle: 'WITCH'
  # Duration until particle is removed in seconds
  duration: 5
  # The style for the particles
  style: 'orbit'
  # The offset Y axis of the particles
  y-offset: 0

# End of config :)