#
# | CraftHolograms by Oribuin |
# | Display the item crafted above a workbench. |
#
# https://github.com/Oribuin/ItemSettings/

# Should the plugin be enabled?
# Default: true
plugin-enabled: true

# List of worlds this feature is disabled in.
disabled-worlds:
  - 'disabled-world-one'
  - 'disabled-world-two'

# Time in seconds until hologram is deleted.
# Default: 5
duration: 5

# Should there be the item displayed above the hologram?
# Default: true
item-display: true

# Should there be a message saying the name of the item crafted in the hologram?
# Default: true
name-display: true

# The hologram name message
# Placeholder:
# {result} represents the item craft name
format: '&7Crafted {result}'

# Message sent when reloading plugin
reload: '&7You have reloaded &bCraftHolograms &7(&a{version}&7(.'
# Invalid permission message
no-permission: '&cYou do not have permission to use this command.'