#
# | CraftHolograms by Oribuin |
# | Display the item crafted above a workbench. |
#
# https://github.com/Oribuin/CraftHolograms/

# Should the plugin be enabled?
# Default: true
plugin-enabled: true

reload: '&7You have reloaded &bCraftHolograms &7(&a{version}&7).'
no-permission: '&cYou do not have permission to use this command.'

# List of worlds this feature is disabled in.
disabled-worlds:
  - 'disabled-world-one'
  - 'disabled-world-two'

# Time in seconds until hologram is deleted.
# Default: 5
duration: 5

# The Y level the hologram will be placed at
# Default: 2.5
y-axis: 2.5

# Should the hologram be deleted if the crafting table is destroyed?
# Default: true
sync-holograms: true

# Should the item crafted by displayed under the text?
# Default: true
item-display: true

# Hologram Format (Supports PlaceholderAPI)
# Result Item Name Placeholder: {result}
hologram-format:
  - '&7[&bCraftHolograms&7]'
  - '&c%player_name%&f, You crafted &c{result}'
