name: EternalCrafting
main: xyz.oribuin.eternalcrafting.EternalCrafting
version: @version@
author: Oribuin
api-version: "1.13"
description: Customize your crafting with special effects and abilities.
website: http://oribuin.xyz/
softdepend: [PlaceholderAPI, HolographicDisplays, PlayerParticles]
commands:
  eternalcraft:
    description: Main Command
    usage: /eternalcraft