name: CraftHolograms
main: xyz.oribuin.craftholos.CraftHolograms
version: @version@
author: Oribuin
api-version: "1.14"
description: Crafting item result previews above crafting table.
website: http://oribuin.xyz/
depend:
  - HolographicDisplays
  - PlaceholderAPI

commands:
  crafthreload:
    description: Reload CraftHolograms.
    usage: /crafthreload